language: php

php:
  - 7.0
  - 7.1

env:
  global:
    - CODECLIMATE_REPO_TOKEN="297fbc2121a7a007123cce9bdfb0db08067d12e0ee2a752e3b538f612e6a55e2"

addons:
  code_climate:
    repo_token: ${CODECLIMATE_REPO_TOKEN}

install:
  - composer update --optimize-autoloader --no-progress --no-interaction

script:
  - build/travis.sh

notifications:
  email: false

after_success:
  - vendor/bin/test-reporter